ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ ru.topbun.ApplicationKt.module ]
    }
}
jwt {
    audience = "topbun"
    secret = ",/lrkhoiu4uiguf9iv,eo"
    issuer = "ru.topbun.tasty"
    realm = "Access to 'api'"
}

database {
    url = "jdbc:h2:./tasty"
    user = "root"
    driver = "org.h2.Driver"
    password = "ldksfm45gbc3J$&^fh8vnrbnbjmrb"
}
